name: Ultimate_Economy
main: ultimate_economy.Ultimate_Economy
author: catch441
version: 1.2.3b

api-version: 1.14

softdepend: [Multiverse-Core,Vault]
loadbefore: [Quests,GriefPrevention,ChestCommands,WorldEdit,Essentials,PlotSquared,MysqlEconomyBank,RepairGui,CommandSigns,DragonSlayer]

permissions:

  ultimate_economy.towninteract:
    description: Allows interaction with all towns.
    default: false

  ultimate_economy.wilderness:
    description: Allows interaction with the wilderness of a townWorld.
    default: false
    
  ultimate_economy.config:
    description: 
    default: op

  ultimate_economy.townworld:
    description: 
    default: op

  ultimate_economy.town:
    description: 
    default: true

  ultimate_economy.adminshop:
    description: 
    default: op

  ultimate_economy.playershop:
    description: 
    default: true
    
  ultimate_economy.rentshop.player:
    description: 
    default: true
    
  ultimate_economy.rentshop.admin:
    description: 
    default: op

  ultimate_economy.jobcenter:
    description: 
    default: op

  ultimate_economy.home:
    description: 
    default: true

  ultimate_economy.pay:
    description: 
    default: true

  ultimate_economy.adminpay:
    description: 
    default: op

  ultimate_economy.info.bank:
    description: 
    default: true

  ultimate_economy.info.money:
    description: 
    default: true

  ultimate_economy.info.shoplist:
    description: 
    default: true

  ultimate_economy.info.myjobs:
    description: 
    default: true

  ultimate_economy.info.jobinfo:
    description: 
    default: true

  ultimate_economy.fastshop:
    description: 
    default: true

commands:

  ue-homes:   
    permission: ultimate_economy.config
    permission-message: You don't have the permission
    description: Enable/disable the homes feature.
    
  ue-language:   
    permission: ultimate_economy.config
    permission-message: You don't have the permission
    description: Change the language of the plugin.

  maxhomes:   
    permission: ultimate_economy.config
    permission-message: You don't have the permission.
    description: Set max homes.
    
  maxRentedDays:   
    permission: ultimate_economy.config
    permission-message: You don't have the permission.
    description: Set max rented days.
    
  maxjobs:   
    permission: ultimate_economy.config
    permission-message: You don't have the permission.
    description: Set max jobs.
    
  townWorld:   
    permission: ultimate_economy.townworld
    permission-message: You don't have the permission.
    description: Activate/deactivate town world.
    
  maxJoinedTowns:   
    permission: ultimate_economy.config
    permission-message: You don't have the permission.
    description: Set max number of towns you can join.
    
  town:   
    permission: ultimate_economy.town
    permission-message: You don't have the permission.
    description: Manage towns.
    
  adminshop:   
    permission: ultimate_economy.adminshop
    permission-message: You don't have the permission.
    description: Manage adminshops.
    
  giveMoney:   
    permission: ultimate_economy.adminpay
    permission-message: You don't have the permission.
    description: Gives a player money without taking it from other players.
    
  ShopList:   
    permission: ultimate_economy.info.shoplist
    permission-message: You don't have the permission.
    description: Shows up a list of all shops.

  jobcenter:   
    permission: ultimate_economy.jobcenter
    permission-message: You don't have the permission.
    description: Manage jobcenter.
    
  jobList:   
    permission: ultimate_economy.info.joblist
    permission-message: You don't have the permission.
    description: Shows up a list of all jobs.
    
  jobInfo:   
    permission: ultimate_economy.info.jobinfo
    permission-message: You don't have the permission.
    description: Shows up information about this job.
 
  myJobs:   
    permission: ultimate_economy.info.myjobs
    permission-message: You don't have the permission.
    description: Shows up all Jobs you already joined.
 
  home:   
    permission: ultimate_economy.home
    permission-message: You don't have the permission.
    description: Teleports you to a homepoint.
    
  setHome:   
    permission: ultimate_economy.home
    permission-message: You don't have the permission.
    description: Set a homepoint.
    
  delHome:   
    permission: ultimate_economy.home
    permission-message: You don't have the permission.
    description: Remove a homepoint.
    
  pay:   
    permission: ultimate_economy.pay
    permission-message: You don't have the permission.
    description: Pay a other player some money.
    
  shop:   
    permission: ultimate_economy.fastshop
    permission-message: You don't have the permission.
    description: Opens a specific shop.
    
  playershop:   
    permission: ultimate_economy.playershop
    permission-message: You don't have the permission.
    description: Manage playershops.
    
  rentshop:   
    permission: ultimate_economy.rentshop.player
    permission-message: You don't have the permission.
    description: Manage rentshops.
    
  money:   
    permission: ultimate_economy.info.money
    permission-message: You don't have the permission.
    description: Shows up your money.
    
  bank:   
    permission: ultimate_economy.info.bank
    permission-message: You don't have the permission.
    description: Enables/disables scoreboard.
    
    