name: Ultimate_Economy
main: ultimate_economy.Ultimate_Economy
version: 1.1.3

api-version: 1.13

softdepend: [Multiverse-Core]

commands:

  maxhomes:   
    permission: ultimate_economy.config
    permission-message: You don't have the permission.
    description: Set max homes.
    
  maxjobs:   
    permission: ultimate_economy.config
    permission-message: You don't have the permission.
    description: Set max jobs.
    
  townWorld:   
    permission: ultimate_economy.config
    permission-message: You don't have the permission.
    description: Activate/deactivate town world.
    
  maxJoinedTowns:   
    permission: ultimate_economy.config
    permission-message: You don't have the permission.
    description: Set max number of towns you can join.
    
  town:   
    permission: ultimate_economy.town
    permission-message: You don't have the permission.
    description: Set max homes.
    
  adminshop:   
    permission: ultimate_economy.adminshop
    permission-message: You don't have the permission.
    description: Manage adminshops.
    
  giveMoney:   
    permission: ultimate_economy.adminpay
    permission-message: You don't have the permission.
    description: Gives a player money without taking it from other players.
    
  ShopList:   
    permission: ultimate_economy.info.shoplist
    permission-message: You don't have the permission.
    description: Shows up a list of all shops.

  jobcenter:   
    permission: ultimate_economy.jobcenter
    permission-message: You don't have the permission.
    description: Manage jobcenter.
    
  jobList:   
    permission: ultimate_economy.info.joblist
    permission-message: You don't have the permission.
    description: Shows up a list of all jobs.
    
  jobInfo:   
    permission: ultimate_economy.info.jobinfo
    permission-message: You don't have the permission.
    description: Shows up information about this job.
 
  myJobs:   
    permission: ultimate_economy.info.myjobs
    permission-message: You don't have the permission.
    description: Shows up all Jobs you already joined.
 
  home:   
    permission: ultimate_economy.home
    permission-message: You don't have the permission.
    description: Teleports you to a homepoint.
    
  setHome:   
    permission: ultimate_economy.home
    permission-message: You don't have the permission.
    description: Set a homepoint.
    
  delHome:   
    permission: ultimate_economy.home
    permission-message: You don't have the permission.
    description: Remove a homepoint.
    
  pay:   
    permission: ultimate_economy.pay
    permission-message: You don't have the permission.
    description: Pay a other player some money.
    
  shop:   
    permission: ultimate_economy.fastshop
    permission-message: You don't have the permission.
    description: Opens a specific shop.
    
  playershop:   
    permission: ultimate_economy.playershop
    permission-message: You don't have the permission.
    description: Manage playershops.
    
  money:   
    permission: ultimate_economy.info.money
    permission-message: You don't have the permission.
    description: Shows up your money.
    
  bank:   
    permission: ultimate_economy.info.bank
    permission-message: You don't have the permission.
    description: Enables/disables scoreboard.
    
    