# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build with Tests

on:
  push:
    branches: [ dev,master ]
  pull_request:
    branches: [ dev,master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    # Runs code climate test coverage
    - name: Code Climate Coverage Action
      uses: paambaati/codeclimate-action@v2.5.5
      with:
        coverageCommand: mvn jacoco:report
        reporter-id:  e9a6854987df94ca96b39bca2e9426927eb5ee08ba9ebf629c156d5f56d31cfc
